# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pentacledata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department_id',
            new_name='department_name',
        ),
    ]
