# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pentacledata', '0002_auto_20181024_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
            ],
        ),
    ]
